import "./globals.css";
import roboto from "./Styles/fonts";

import Nav from "./Components/Nav";
import Footer from "./Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Nav />
        <div className="min-h-screen">{children}</div>
        <Footer className="fixed bottom-0" />
      </body>
    </html>
  );
}
