import "./globals.css";
import { League_Spartan } from "next/font/google";

import Nav from "./Components/Nav";
import Footer from "./Components/Footer";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        <Nav />
        <div className="min-h-screen">{children}</div>
        <Footer className="fixed bottom-0" />
      </body>
    </html>
  );
}
